- name: play level variables
  hosts: localhost
  connection: local
  vars:
    COURSE: Devops with AWS
    DURATION: 10 hrs
    TRAINER: Shivakumar
  tasks:
  - name: print course information
    vars:
      COURSE: Ansible
    ansible.builtin.debug:
    #vars reference should be surrounded by ""
        msg: "Hello {{ COURSE }}, course duration: {{ DURATION }}, trainer is {{ TRAINER }}"
  
  - name: print course information
    ansible.builtin.debug:
      #vars reference should be surrounded by ""
      msg: "Hello {{ COURSE }}, course duration: {{ DURATION }}, trainer is {{ TRAINER }}"