- name: variables from files
  hosts: localhost
  connection: local
  vars_files:
    - course.yaml

  tasks:
    - name: print course information
      ansible.builtin.debug:
        msg: "Hello I'm learning {{ COURSE }}, Duration: {{ DURATION }}, Trainer is: {{ TRAINER }}"
