- name: variables from prompt
  hosts: localhost
  connection: local

  vars_prompt:
    - name: USERNAME
      prompt: please enter your username
      private: false

    - name: PASSWORD
      prompt: please enter your password
      private: false
      
  tasks:
    - name: printing user information
      ansible.builtin.debug:
        msg: "Hello user name is: {{ USERNAME }}, and password is: {{ PASSWORD }}"