- name: variables from prompt
  host: localhost
  connection: local
  vars_prompt:
    - name: USERNAME
      prompt: please enter your username
      private: true

    - name: PASSWORD
      prompt: please enter your password
      private: true
      
      tasks:
      - name: printing user information
        ansible.builtin.debug:
          msg: "Hello user name is: {{ USERNAME }}, and password is: {{ PASSWORD }}"