- name: playbook control using ansible facts
  hosts: local
  connection: local
  become: yes
  tasks:
    - name: Install nginx if redhat
      ansible.builtin.dnf:
        name: nginx
        state: present
      when: ansible_facts['os_family'] == "RedHat" 

    - name: Install nginx if debian
      ansible.builtin.apt:
        name: nginx
        state: present
      when: ansible_facts['os_family'] == "Debian"

    - name: Start and enable Nginx
      ansible.builtin.systemd:
        name: nginx
        state: started
        enabled: yes