- name: loop packages
  hosts: local
  become: yes
  tasks:
    - name: Install selected packages
      ansible.builtin.package:
        name: "{{ item }}"
        state: present
      loop:
      - nginx
      - python3
      - mysql
      when: ansible_facts['os_family'] == "RedHat"  