- name: funtions
  hosts: local
  connection: local
  gather_facts: false

  vars:
    person: "Shiva"
    
  tasks:
    - name: call person
      ansible.builtin.debug:
        msg: "Hello, {{ Person }}"