- name: Greet Person Function Example
  hosts: localhost
  connection: local
 
  tasks:
    - name: call person details
      ansible.builtin.debug:
        "Hello I'm learning {{ COURSE }}, course duration: {{ DURATION }}, trainer is {{ TRAINER }}"
