- name: Function 
  hosts: local
  connection: local
  vars:
    PERSONS: "Shiva,Ramesh,Suresh"
  tasks:
    # - name: check undefined variable
    #   ansible.builtin.debug:
    #     msg: "Hello, {{ Person | default('Shiva') }}"

    - name: print names
      ansible.builtin.debug:
        msg: "Hello, {{ PERSONS | split(',') }}"

    - name: convert map in to list
      course: 
        name: Ansible
        duration: 10 hrs
        trainer: siva kumar
      ansible.builtin.debug:
        msg: "Couse info: {{ course | dict2items }}"

