- name: Greet Person Function Example
  hosts: localhost
  connection: local
  gather_facts: false

  vars:
    Person: "Shiva"

  tasks:
    - name: call person
      ansible.builtin.debug:
        msg: "Hello, {{ Person }}"
