- name: Create EC2 instances and Route 53 records
  hosts: localhost
  connection: local
  gather_facts: false

  vars:
    instances:
      - mysql
      - backend
      - frontend
    subnet_id: subnet-0bc7656219c9a896d
    sg_id: sg-010eb25d82d15b248
    image_id: ami-09c813fb71547fc4f
    instance_type: t3.micro
    zone: daws84ss.site

  tasks:
    - name: Create EC2 instances
      amazon.aws.ec2_instance:
        name: "{{ item }}"
        vpc_subnet_id: "{{ subnet_id }}"
        instance_type: "{{ instance_type }}"
        security_groups:
          - "{{ sg_id }}"
        image_id: "{{ image_id }}"
        wait: true
        tags:
          Name: "{{ item }}"
      loop: "{{ instances }}"
      register: ec2_output

    - name: Print ec2_output
      ansible.builtin.debug:
        msg: ec2_output

    - name: Create R53 records
      amazon.aws.route53:
        state: present
        zone: "{{ zone }}"
        record: "{{ zone }}"
        type: A
        ttl: 1
        value: "{{ item.instances[0].public_ip_address }}"
        wait: true
        overwrite: true
      loop: "{{ ec2_output.results }}"
      when: item.item == "frontend"